#!/bin/bash
### UNIVERSAL ELEMENT MATRIX CLIENT INSTALLER BY HHK02 (ISAACFHL)

answer=""

# Check if are  you root.
if [[ $EUID -eq 0 ]]; then
    echo "Welcome to Element Matrix Client Installer by hhk02"
    echo "WARNING! This is a unofficial installer"
    echo "I created this for install Element Desktop if your distro doesn't have a package for install it."
    read -r -p "Are you sure install Element Desktop ?" answer

    if [ $answer = "yes" ]; then
    echo "Downloading Element....."
    # Download Element deb package from official website
    if [ -f /usr/bin/wget ]; then
        if [ -f 'element-desktop.tar.gz' ]; then
            echo "Skip download.... file alredy exists!"
        else
            wget https://packages.element.io/desktop/install/linux/glibc-x86-64/element-desktop.tar.gz
        fi
    else
        if [ -f /usr/bin/apt ]; then
            apt install wget -y
        fi
        if [ -f /usr/bin/dnf ]; then
            dnf install wget -y
        fi
        if [ -f /usr/bin/pacman ]; then
            pacman -S wget --no-confirm
        fi
    fi
    echo "Extracting Element Desktop"
    # Extract Element files in root dir
    mkdir -p /opt/Element
    tar xvf element-desktop.tar.gz --directory=/opt/Element
    # Make a symlink for run Element in the terminal.
    ln -s /opt/Element/element-desktop /usr/bin/element-desktop
    # Update menu list apps
    echo "Updating applications list"
    update-desktop-database
    echo "Done"
    else
    echo "Canceled by user!"
    fi
# If it's not root
else
    echo "ERROR : Please use this script as ROOT!"
fi
