#!/bin/bash
### UNIVERSAL ELEMENT MATRIX CLIENT INSTALLER BY HHK02 (ISAACFHL)

answer=""

# Check if are  you root.
if [[ $EUID -eq 0 ]]; then
    echo "Welcome to Element Matrix Client Installer by hhk02"
    echo "WARNING! This is a unofficial installer"
    echo "I created this for install Element Desktop if your distro doesn't have a package for install it."
    read -r -p "Are you sure install Element Desktop ?" answer

    if [ $answer = "yes" ]; then
    echo "Downloading Element....."
    # Download Element deb package from official website
    if [ -f /usr/bin/wget ]; then
        if [ -f 'element-desktop_1.11.15_amd64.deb' ]; then
            echo "Skip download.... file alredy exists!"
        else
            wget https://packages.element.io/debian/pool/main/e/element-desktop/element-desktop_1.11.15_amd64.deb
        fi
    else
        dnf install wget -y
    fi
    if [ -f /usr/bin/ar ]; then
        echo "ar command found"
    else
        dnf install binutils -y
    fi
    ar -x element-*.deb
    echo "Extracting Element Desktop"
    # Extract Element files in root dir
    tar xvf data.tar.xz --directory=/
    # Make a symlink for run Element in the terminal.
    ln -s /opt/Element/element-desktop /usr/bin/element-desktop
    # Update menu list apps
    echo "Updating applications list"
    update-desktop-database
    echo "Done"
    else
    echo "Canceled by user!"
    fi
# If it's not root
else
    echo "ERROR : Please use this script as ROOT!"
fi
